### ISSUE TITLE
Check examples

### ISSUE THREAD

**Issue by seanturner** [lamps-wg/cms-kyber#18]
While doing the examples, see [here](https://github.com/lamps-wg/kyber-certificates/pull/58/files) and [here](https://github.com/lamps-wg/kyber-certificates/pull/61), I noticed that they private key in this I-D seems to be lot bigger than the certificates examples.  Is the private key here just the seed?

**Comment by danvangeest** [comment]
You are right.  I made these examples before kyber-certificates specified use of the seed,  In fact, my crypto library developer has pushed back against using the private key seed, so when kyber-certificates is updated I'll have something to show him to prove it's a requirement.
